// <auto-generated />
using System;
using Backup.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backup.Infrastructure.Migrations
{
    [DbContext(typeof(BackupDbContext))]
    [Migration("20260514011945_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backup.Core.Entities.BackupChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("ParentId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<Guid>("ServerBackupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ServerBackupId");

                    b.ToTable("BackupChannels", (string)null);
                });

            modelBuilder.Entity("Backup.Core.Entities.BackupMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<decimal>("MessageId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.ToTable("BackupMessages", (string)null);
                });

            modelBuilder.Entity("Backup.Core.Entities.BackupRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Color")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Permissions")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<decimal>("RoleId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<Guid>("ServerBackupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ServerBackupId");

                    b.ToTable("BackupRoles", (string)null);
                });

            modelBuilder.Entity("Backup.Core.Entities.ServerBackup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("GuildName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ServerBackups", (string)null);
                });

            modelBuilder.Entity("Backup.Core.Entities.BackupChannel", b =>
                {
                    b.HasOne("Backup.Core.Entities.ServerBackup", "ServerBackup")
                        .WithMany("Channels")
                        .HasForeignKey("ServerBackupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServerBackup");
                });

            modelBuilder.Entity("Backup.Core.Entities.BackupMessage", b =>
                {
                    b.HasOne("Backup.Core.Entities.BackupChannel", "Channel")
                        .WithMany("Messages")
                        .HasForeignKey("ChannelId")
                        .HasPrincipalKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("Backup.Core.Entities.BackupRole", b =>
                {
                    b.HasOne("Backup.Core.Entities.ServerBackup", "ServerBackup")
                        .WithMany("Roles")
                        .HasForeignKey("ServerBackupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServerBackup");
                });

            modelBuilder.Entity("Backup.Core.Entities.BackupChannel", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Backup.Core.Entities.ServerBackup", b =>
                {
                    b.Navigation("Channels");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
